const allMorningSteps = [
  {
    stepNumber: 0,
    routineStep: "Makeup Remover and Oil Cleanser",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 1,
    routineStep: "Water Based Cleanser",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 2,
    routineStep: "Exfoliator",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 3,
    routineStep: "Toner",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 4,
    routineStep: "Essence",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 5,
    routineStep: "Treatments",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 6,
    routineStep: "Sheet Masks",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 7,
    routineStep: "Eye Cream",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 8,
    routineStep: "Moisturizer",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 9,
    routineStep: "Sun Protection",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
  },
];

const allNightSteps = [
  {
    stepNumber: 11,
    routineStep: "Makeup Remover and Oil Cleanser",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 12,
    routineStep: "Water Based Cleanser",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 13,
    routineStep: "Exfoliator",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 14,
    routineStep: "Toner",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 15,
    routineStep: "Essence",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 16,
    routineStep: "Treatments",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 17,
    routineStep: "Sheet Masks",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 18,
    routineStep: "Eye Cream",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
  {
    stepNumber: 19,
    routineStep: "Moisturizer",
    timeOfDay: "night",
    productId: null,
    stepId: null,
  },
];

module.exports = { allMorningSteps, allNightSteps };
