const BASE_URL = process.env.REACT_APP_BASE_URL || "http://localhost:3001";

const allMorningSteps = [
  {
    stepNumber: 0,
    routineStep: "Makeup Remover and Oil Cleanser",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-01.png`,
  },
  {
    stepNumber: 1,
    routineStep: "Water Based Cleanser",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-02.png`,
  },
  {
    stepNumber: 2,
    routineStep: "Exfoliator",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-03.png`,
  },
  {
    stepNumber: 3,
    routineStep: "Toner",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-04.png`,
  },
  {
    stepNumber: 4,
    routineStep: "Essence",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-05.png`,
  },
  {
    stepNumber: 5,
    routineStep: "Treatments",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-06.png`,
  },
  {
    stepNumber: 6,
    routineStep: "Sheet Masks",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-07.png`,
  },
  {
    stepNumber: 7,
    routineStep: "Eye Cream",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-08.png`,
  },
  {
    stepNumber: 8,
    routineStep: "Moisturizer",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-09.png`,
  },
  {
    stepNumber: 9,
    routineStep: "Sun Protection",
    timeOfDay: "morning",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-10.png`,
  },
];

const allNightSteps = [
  {
    stepNumber: 11,
    routineStep: "Makeup Remover and Oil Cleanser",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-01.png`,
  },
  {
    stepNumber: 12,
    routineStep: "Water Based Cleanser",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-02.png`,
  },
  {
    stepNumber: 13,
    routineStep: "Exfoliator",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-03.png`,
  },
  {
    stepNumber: 14,
    routineStep: "Toner",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-04.png`,
  },
  {
    stepNumber: 15,
    routineStep: "Essence",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-05.png`,
  },
  {
    stepNumber: 16,
    routineStep: "Treatments",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-06.png`,
  },
  {
    stepNumber: 17,
    routineStep: "Sheet Masks",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-07.png`,
  },
  {
    stepNumber: 18,
    routineStep: "Eye Cream",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-08.png`,
  },
  {
    stepNumber: 19,
    routineStep: "Moisturizer",
    timeOfDay: "night",
    productId: null,
    stepId: null,
    image_url: `${BASE_URL}/Skincare-Icons-09.png`,
  },
];

module.exports = { allMorningSteps, allNightSteps };
